apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: hello-k3s
  namespace: default
spec:
  secretName: hello-k3s-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: hello-k3s.a.uber5.com
  dnsNames:
  - hello-k3s.a.uber5.com
