apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-slash-opt
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: BasePath
        value: "/opt/k3s-local-storage"
      - name: StorageType
        value: "hostpath"
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
