---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3sle-monitoring-prometheus-data
  labels:
    type: local
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus/monitoring"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3sle-monitoring-alertmanager-data
  labels:
    type: local
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus/alertmanager-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3sle-monitoring-grafana-data
  labels:
    type: local
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus/grafana-data"
