kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vol-striped1
  namespace: backup-test
spec:
  storageClassName: openebs-sc1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
